CREATE TABLE sesion (
   id_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
   ultimo_acceso TIMESTAMP NOT NULL
);

CREATE TABLE clase (
   id_clase INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
   nombre VARCHAR NOT NULL
);

CREATE TABLE primitivo (
   id_primitivo INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
   nombre VARCHAR NOT NULL
);

INSERT INTO primitivo (nombre) VALUES ('String');
INSERT INTO primitivo (nombre) VALUES ('int');
INSERT INTO primitivo (nombre) VALUES ('byte');
INSERT INTO primitivo (nombre) VALUES ('short');
INSERT INTO primitivo (nombre) VALUES ('long');
INSERT INTO primitivo (nombre) VALUES ('float');
INSERT INTO primitivo (nombre) VALUES ('double');
INSERT INTO primitivo (nombre) VALUES ('char');
INSERT INTO primitivo (nombre) VALUES ('boolean');

CREATE TABLE objeto (
   id_objeto INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
   id_sesion INTEGER,
   id_clase INTEGER NOT NULL
);

ALTER TABLE objeto 
ADD FOREIGN KEY (id_sesion) REFERENCES sesion (id_sesion);

ALTER TABLE objeto 
ADD FOREIGN KEY (id_clase) REFERENCES clase (id_clase);

CREATE TABLE atributo (
   id_atributo INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
   nombre VARCHAR NOT NULL,
   id_clase INTEGER NOT NULL,
   id_tipo_clase INTEGER,
   id_tipo_primitivo INTEGER,
   es_coleccion BOOLEAN NOT NULL,
);

ALTER TABLE atributo
ADD FOREIGN KEY (id_clase) REFERENCES clase (id_clase);

ALTER TABLE atributo
ADD FOREIGN KEY (id_tipo_clase) REFERENCES clase (id_clase);

ALTER TABLE atributo
ADD FOREIGN KEY (id_tipo_primitivo) REFERENCES primitivo (id_primitivo);

CREATE TABLE valor (
   id_valor INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
   id_objeto INTEGER NOT NULL,
   id_atributo INTEGER NOT NULL,
   valor_primitivo VARCHAR,
   id_objeto_valor INTEGER
);

ALTER TABLE valor
ADD FOREIGN KEY (id_objeto) REFERENCES objeto (id_objeto);

ALTER TABLE valor
ADD FOREIGN KEY (id_objeto_valor) REFERENCES objeto (id_objeto);

ALTER TABLE valor
ADD FOREIGN KEY (id_atributo) REFERENCES atributo (id_atributo);