INSERT INTO SESION (ULTIMO_ACCESO) VALUES(CURRENT_TIMESTAMP);

INSERT INTO CLASE (NOMBRE) VALUES('Persona');
INSERT INTO CLASE (NOMBRE) VALUES('Direccion');

INSERT INTO OBJETO (ID_SESION, ID_CLASE) VALUES(1, 1);
INSERT INTO OBJETO (ID_SESION, ID_CLASE) VALUES(NULL, 2);
INSERT INTO OBJETO (ID_SESION, ID_CLASE) VALUES(NULL, 2);
INSERT INTO OBJETO (ID_SESION, ID_CLASE) VALUES(NULL, 2);

INSERT INTO ATRIBUTO (NOMBRE, ID_CLASE, ID_TIPO_CLASE, ID_TIPO_PRIMITIVO, ES_COLECCION) VALUES('dni', 1, NULL, 2, FALSE);
INSERT INTO ATRIBUTO (NOMBRE, ID_CLASE, ID_TIPO_CLASE, ID_TIPO_PRIMITIVO, ES_COLECCION) VALUES('nombre', 1, NULL, 1, FALSE);
INSERT INTO ATRIBUTO (NOMBRE, ID_CLASE, ID_TIPO_CLASE, ID_TIPO_PRIMITIVO, ES_COLECCION) VALUES('laMejorDireccion', 1, 2, NULL, FALSE);
INSERT INTO ATRIBUTO (NOMBRE, ID_CLASE, ID_TIPO_CLASE, ID_TIPO_PRIMITIVO, ES_COLECCION) VALUES('telefonos', 1, NULL, 1, TRUE);
INSERT INTO ATRIBUTO (NOMBRE, ID_CLASE, ID_TIPO_CLASE, ID_TIPO_PRIMITIVO, ES_COLECCION) VALUES('direcciones', 1, 2, NULL, TRUE);
INSERT INTO ATRIBUTO (NOMBRE, ID_CLASE, ID_TIPO_CLASE, ID_TIPO_PRIMITIVO, ES_COLECCION) VALUES('calle', 2, NULL, 1, FALSE);
INSERT INTO ATRIBUTO (NOMBRE, ID_CLASE, ID_TIPO_CLASE, ID_TIPO_PRIMITIVO, ES_COLECCION) VALUES('numero', 2, NULL, 2, FALSE);
INSERT INTO ATRIBUTO (NOMBRE, ID_CLASE, ID_TIPO_CLASE, ID_TIPO_PRIMITIVO, ES_COLECCION) VALUES('codigoPostal', 2, NULL, 1, FALSE);
INSERT INTO ATRIBUTO (NOMBRE, ID_CLASE, ID_TIPO_CLASE, ID_TIPO_PRIMITIVO, ES_COLECCION) VALUES('localidad', 2, NULL, 1, FALSE);
INSERT INTO ATRIBUTO (NOMBRE, ID_CLASE, ID_TIPO_CLASE, ID_TIPO_PRIMITIVO, ES_COLECCION) VALUES('provincia', 2, NULL, 1, FALSE);
INSERT INTO ATRIBUTO (NOMBRE, ID_CLASE, ID_TIPO_CLASE, ID_TIPO_PRIMITIVO, ES_COLECCION) VALUES('pais', 2, NULL, 1, FALSE);

INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(1, 1, '123', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(1, 2, 'Pepe', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(1, 3, NULL, 2);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(2, 6, 'Cuenca', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(2, 7, '1235', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(2, 8, 'C1245DQW', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(2, 9, 'CABA', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(2, 10, 'CABA', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(2, 11, 'Argentina', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(1, 4, '4444-2222', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(1, 4, '5555-3333', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(1, 4, '6666-4444', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(3, 6, 'Corrientes', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(3, 7, '452', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(3, 8, 'B5514ABC', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(3, 9, 'Buenos Aires', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(3, 10, 'Buenos Aires', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(3, 11, 'Argentina', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(4, 6, 'Pedro Moran', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(4, 7, '2345', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(4, 8, 'ABC123', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(4, 9, 'Buzios', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(4, 10, 'Rio de Janeiro', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(4, 11, 'Brasil', NULL);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(1, 5, NULL, 3);
INSERT INTO VALOR (ID_OBJETO, ID_ATRIBUTO, VALOR_PRIMITIVO, ID_OBJETO_VALOR) VALUES(1, 5, NULL, 4);